using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum GameInterludeServerPacketType : byte
{
    InterludeKeyPacket = 0x00,
    CharSelectionInfo = 0x13,
    CharTemplate = 0x17,
    CharCreateOk = 0x19,
    CharCreateFail = 0x1A,
    CharSelected = 0x15,
    SkillList = 0x58,
    UserInfo = 0x04,
    SkillCoolTime = 0xC1,
    MacroList = 0xE7,
    BuyList = 0x11,
    ShopPreviewList = 0xef,
    ShopPreviewInfo = 0xf0,
    MultiSellList = 0xd0,
    SellList = 0x10,
    WhDepositList = 0x41,
    PackageSendableList = 0xC3,
    WhWithdrawList = 0x42,
    BuyListSeed = 0xE8,
    NpcHtmlMessage = 0x0F,
    PackageToList = 0xC2,
    TutorialShowHtml = 0xa0,
    ShortCutInit = 0x45,
    ShortCutRegister = 0x44,
    ShortCutDel = 0x46,
    HennaInfo = 0xE4,
    QuestList = 0x80,
    PledgeShowMemberListUpdate = 0x54,
    PledgeShowMemberListAll = 0x53,
    PledgeInfo = 0x83,
    ManagePledgePower = 0x30,
    PledgeStatusChanged = 0xcd,
    NpcInfo = 0x16,
    DeleteObject = 0x12,
    CharMoveToLocation = 0x01,
    FriendList = 0xFA,
    ValidateLocation = 0x61,
    EtcStatusUpdate = 0xF3,
    ExTypePacket = 0xfe,
    StatusUpdate = 0x0E,
    TargetUnselected = 0x2A,
    SocialAction = 0x2D,
    TeleportToLocation = 0x28,
    Revive = 0x07,
    AbnormalStatusUpdate = 0x7f,
    AcquireSkillList = 0x8a,
    AcquireSkillInfo = 0x8b
}
